require("prototypes.entities.harvester")
require("prototypes.entities.pipes")
require("prototypes.entities.plasma-thruster")
--require("prototypes.entities.tile")
--require("prototypes.entities.silo")
--require("prototypes.entities.landing-pad")
--require("prototypes.entities.flying-bot-temp")